# Generated by Django 2.2 on 2020-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0006_auto_20200422_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='items',
            field=models.ManyToManyField(to='FirstWebApp.OrderItem'),
        ),
    ]
