# Generated by Django 2.2 on 2020-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0011_auto_20200423_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail',
            name='items',
            field=models.ManyToManyField(to='FirstWebApp.OrderItem'),
        ),
    ]
