# Generated by Django 2.2 on 2020-04-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0012_auto_20200423_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='current_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip+', to='FirstWebApp.CheckoutDetail'),
        ),
    ]
