# Generated by Django 2.2 on 2020-04-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0013_auto_20200428_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address+', to='FirstWebApp.CheckoutDetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip+', to='FirstWebApp.CheckoutDetail'),
        ),
    ]
