# Generated by Django 2.2 on 2020-04-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0014_auto_20200428_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state+', to='FirstWebApp.CheckoutDetail'),
        ),
    ]
