# Generated by Django 2.2 on 2020-04-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0015_auto_20200428_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
