# Generated by Django 2.2 on 2020-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0016_auto_20200428_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(to='FirstWebApp.CheckoutDetail'),
        ),
    ]
