# Generated by Django 2.2 on 2020-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0018_remove_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='items',
            field=models.ManyToManyField(to='FirstWebApp.OrderItem'),
        ),
    ]
