# Generated by Django 2.2 on 2020-05-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebApp', '0020_order_checkoutdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='items',
        ),
    ]
